#set page(width: 8.5in, height: 39in)
#show link: set text(fill: rgb("#005ad9"))

== Zeeman and Hyperfine
Deval Deliwala

The spin Hamiltonian $scr(H)$ governs the spin physics of recombination. It is
what we need to implement before simulating EDMR.

$scr(H)$ is a sum of the
#link("http://hyperphysics.phy-astr.gsu.edu/hbase/quantum/zeeman.html")[Zeeman effect],
#link("https://bohr.physics.berkeley.edu/classes/221/1112/notes/hyperfine.pdf")[hyperfine interactions],
#link("https://en.wikipedia.org/wiki/Zero-field_splitting")[zero-field splitting],
and the
#link("https://en.wikipedia.org/wiki/Exchange_interaction")[exchange interaction].

$
scr(H)
= hat(H)_("Z")
+ hat(H)_("HF")
+ hat(H)_("ZFS")
+ hat(H)_("EX")
$

Normally $scr(H)$ also includes a
#link("https://chem.libretexts.org/Bookshelves/Physical_and_Theoretical_Chemistry_Textbook_Maps/Supplemental_Modules_(Physical_and_Theoretical_Chemistry)/Spectroscopy/Magnetic_Resonance_Spectroscopies/Nuclear_Magnetic_Resonance/NMR_-_Theory/NMR_Interactions/Quadrupolar_Coupling")[nuclear quadrupole interaction]
term. In 4H-SiC, there are no nuclei with nuclear spin $I > 1/2$, so we set that
term to zero.

The goal of this post is to derive the first two Hamiltonian terms. The next two
are reviewed in the next post.

I use a fancy $scr(H)$ to represent the full spin Hamiltonian. Sub-Hamiltonians
are normal $H$'s but with hats (for example, $hat(H)_Z$).

=== The Zeeman Effect

$hat(H)_Z$ determines how spin-state energies split in the presence of an
external magnetic field $arrow(B)$. It is the dominant term in the spin
Hamiltonian that drives recombination.

A spinning charged particle is a magnetic dipole. Its magnetic dipole moment
$arrow(mu)$ is proportional to its spin angular momentum $arrow(S)$:

$
arrow(mu) = gamma arrow(S).
$

The proportionality constant $gamma$ is the gyromagnetic ratio. From the Dirac
equation it can be shown

$
arrow(mu)
= gamma arrow(S)
= -g (q / (2 m_e)) arrow(S)
= -((g mu_B) / planck) arrow(S),
$

where $g approx 2.0023$ is the Landé $g$-factor for the free electron and
$mu_B approx 9.2 dot 10^(-24) "J/T"$ is the Bohr magneton.

When a magnetic dipole is placed in a magnetic field $arrow(B)$, it experiences
a torque $arrow(mu) times arrow(B)$ which tends to align it with the field like
a compass. The energy associated with this torque is

$
H = -arrow(mu) dot arrow(B) = -gamma arrow(B) dot arrow(S).
$

Therefore, the Zeeman Hamiltonian is

$
hat(H)_Z
= -arrow(mu) dot arrow(B)_0
= ((g mu_B) / planck) arrow(S) dot arrow(B)_0
= (g mu_B) / planck B_0 S_z
$

where $S_z = (planck / 2) hat(sigma)_z$ and $sigma_z$ is the Pauli-$z$ spin
matrix. Applying $hat(H)_Z$ on a spin state $|s, m_s⟩$ gives

$
hat(H)_Z |s, m_s⟩
= (g mu_B) / planck B_0 S_z |s, m_s⟩
$

$
= (g mu_B )/ planck B_0 (m_s planck) |s, m_s⟩
= m_s g mu_B B_0 |s, m_s⟩.
$

From the equation above, we can calculate $hat(H)_Z$'s effect on any spin state
$|s, m_s⟩$.

#box(
  fill: luma(250),
  inset: 10pt,
  width: 100%,
  [
    #align(center)[
      #image("/nasa_edmr_sim/zeeman.svg", width: 50%)
    ]
  ],
)

Ordinarily we use an anisotropic $g$-tensor. Magnetic fields in different
directions act differently on $|s, m_s⟩$. In that case,

$
hat(H)_Z = mu_B arrow(S) dot g dot arrow(B)_0.
$

This can be diagonalized along the principal axis:

$
g_("diag") = mat(
  g_x, 0, 0;
  0, g_y, 0;
  0, 0, g_z;
).
$

For our simulation, we start with $g approx 2.0023$. Our Zeeman Hamiltonian is

#box(
  fill: luma(250),
  inset: 10pt,
  width: 100%,
  [
$
hat(H)_Z |s, m_s⟩ = m_s g mu_B B_0 |s, m_s⟩.
$
  ],
)

=== Hyperfine Interaction

The hyperfine interaction comes from the magnetic field generated by the nucleus
$arrow(B)(arrow(r))$ acting on the magnetic moment of an orbiting electron. We
will calculate $arrow(B)(arrow(r))$ and use the dipole energy to construct
$hat(H)_("HF")$.

Maxwell's equations say

$
nabla dot arrow(B) = 0, quad nabla times arrow(B) = mu_0 arrow(J).
$

==== Vector Potential

The first equation tells us there are no magnetic monopoles; the magnetic field
$arrow(B)$ has zero divergence. From vector calculus this means there exists a
vector field $arrow(A)$ such that

$
arrow(B) = nabla times arrow(A).
$

$arrow(A)$ is not unique, but to make the math simple we can impose the Coulomb
gauge condition $nabla dot arrow(A) = 0$. Substituting yields

$
nabla^2 arrow(A) = -mu_0 arrow(J).
$

==== Current Density

$arrow(J)$ is the current density. If we model a localized nuclear magnetic
moment $arrow(mu)_n$ at the origin, it generates an effective current density

$
arrow(J)_n(arrow(r)') = nabla' times [arrow(mu)_n delta^3(arrow(r)')].
$

The general solution for $arrow(A)$ is

$
arrow(A)(arrow(r))
= mu_0 / (4 pi) integral d^3 r' arrow(J)_n(arrow(r)' / abs(arrow(r) - arrow(r)'))
$

$
= mu_0 / (4 pi) arrow(mu)_n times nabla(1 / r)
= mu_0 / (4 pi) (arrow(mu)_n times arrow(r)) / r^3.
$

Then, using the identity

$
nabla times (arrow(a) times arrow(r) f(r))
= arrow(a) nabla dot (arrow(r) f)
- (arrow(a) dot nabla)(arrow(r) f),
$

with $arrow(a) = arrow(mu)_n$ and $f(r) = 1 / r^3$, we get the canonical
expression for a magnetic field from a dipole in classical electrodynamics:

$
arrow(B)(arrow(r))
= mu_0 / (4 pi r^3) [3 (arrow(mu)_n dot hat(r)) hat(r) - arrow(mu)_n]
+ (2 mu_0) / 3 arrow(mu)_n delta^3(arrow(r)).
$

==== Hamiltonian Density

A magnetic moment $arrow(mu)_e$ at $arrow(r)$ has energy

$
U(arrow(r)) = -arrow(mu)_e dot arrow(B)(arrow(r)).
$

Substituting $arrow(B)(arrow(r))$ with the expression above, we can separate the
energy into two terms:

$
U_("dipolar")(arrow(r))
= -arrow(mu)_e dot
  [(mu_0 / (4 pi r^3)) (3 (arrow(mu)_n dot hat(r)) hat(r) - arrow(mu)_n)],
$

$
U_("contact")(arrow(r))
= -arrow(mu)_e dot [((2 mu_0 )/ 3) arrow(mu)_n delta^3(arrow(r))].
$

Promoting magnetic moments to their quantum operators,

$
arrow(mu)_e = -g_e mu_B hat(S) / planck, quad
arrow(mu)_n = +g_n mu_N hat(I) / planck,
$

where the Bohr magneton $mu_B = (e planck) / (2 m_e)$ and the nuclear magneton
$mu_N = (e planck) / (2 m_p)$.

Now substitute into the energy expression to get the Hamiltonian of the electron
in the magnetic field generated by the nucleus:

$
H(arrow(r))
= mu_0 / (4 pi) (g_e mu_B g_n mu_N )/ planck^2
  (
    (arrow(S) dot arrow(I) - 3 (arrow(S) dot hat(r)) (arrow(I) dot hat(r))) / r^3
    + (8 pi )/ 3 delta^3(arrow(r)) (arrow(S) dot arrow(I))
  ).
$

The prefactor is a constant. Call it $C$. If an electron occupies a spatial
wavefunction $psi(arrow(r))$, the full hyperfine Hamiltonian is

$
hat(H)_("HF") = ∫ d^3 r \, abs(psi(arrow(r)))^2 H(arrow(r)).
$

Now write the Hamiltonian in index form:

$
H(arrow(r))
= C
  [
    1 / r^3 (delta_(k l) - 3 hat(r)_k hat(r)_l) S_k I_l
    + (8 pi) / 3) delta^3(arrow(r) S_k I_k
  ],
$

where we sum over repeated indices. The final expression to solve is

$
hat(H)_("HF")
= C
  [
    underbrace(
      S_k I_l ∫ d^3 r abs(psi(arrow(r)))^2 (delta_(k l) - 3 hat(r)_k hat(r)_l) / r^3
    , "dipolar term")
    +
    underbrace(
      (8 pi) / 3 S_k I_k ∫ d^3 r abs(psi(arrow(r)))^2 delta^3(arrow(r))
    , "contact (isotropic) term")
  ].
$

The contact term reduces to

$
(8 pi) / 3 S_k I_k ∫ d^3 r abs(psi(arrow(r)))^2 delta^3(arrow(r))
&= (8 pi )/ 3 abs(psi(0))^2 S_k I_k \ 
&= A_("iso") delta_(k l) S_k I_l,
$

where $A_("iso") = C ((8 pi) / 3) abs(psi(0))^2$.

To solve the dipolar term, define

$
A_(k l)^("dip")
= C ∫ d^3 r \, abs(psi(arrow(r)))^2 (delta_(k l) - 3 hat(r)_k hat(r)_l) / r^3.
$

Then the dipolar term reduces to $S_k I_l A_(k l)^("dip")$. Define the $A_(i j)$
tensor as

$
A_(i j) = A_("iso") delta_(i j) + A_(i j)^("dip").
$

Finally,

#box(
  fill: luma(250),
  inset: 10pt,
  width: 100%,
  [
$
hat(H)_("HF") = hat(S) dot A dot hat(I) = hat(S)_i A_(i j) hat(I)_j.
$
  ],
)

For multiple nuclei, like in silicon carbide, we sum over every $j$ inequivalent
nucleus:

$
hat(H)_("HF") = sum_j hat(arrow(S)) dot A_j dot hat(arrow(I))_j.
$

For a two-nucleus (silicon + carbon) and two-electron (defect + carrier)
system, the Hilbert space is $2^4 = 16$ dimensional. The hyperfine Hamiltonian
is a $16 times 16$ matrix.

Making a $B_0$ versus energy plot for hyperfine, like with Zeeman above, is
difficult. In a future post, we'll generate it. I will be writing eigen-energy
simulations to show what the hyperfine interaction does to the 16 basis states
defining our spin system.

