#set page(width: 8.5in, height: 27in)
#show link: set text(fill: rgb("#005ad9"))

== Zero-Field Splitting 
Deval Deliwala

We derived the
Zeeman and hyperfine Hamiltonians. This post derives the next term: zero-field
splitting (ZFS). The next post derives the exchange interaction and then combines
everything into a full spin Hamiltonian.

I use $scr(H)$ for the full spin Hamiltonian. Sub-Hamiltonians are written as
hatted $H$'s (for example, $hat(H)_Z$).


Zero-field splitting (ZFS) comes from one electron’s spin generating a magnetic
field that acts on another electron’s magnetic moment. Even with no external
magnetic field, this dipole–dipole interaction shifts spin energy levels. ZFS is
an electron–electron analog of the hyperfine interaction.

We start from the magnetic field of a point dipole derived in the previous note:

$
arrow(B)(arrow(r))
= underbrace(
    mu_0 / (4 pi r^3)
    [3 (arrow(mu)_n dot hat(r)) hat(r) - arrow(mu)_n]
  , upright("dipolar term"))
+ underbrace(
    (2 mu_0 )/ 3 arrow(mu)_n delta^3(arrow(r))
  , upright("contact (isotropic) term")).
$

The contact term arises from a point-like nucleus. For electron–electron
interactions, electrons do not coincide exactly, so there is no delta-contact
term. Only the $1/r^3$ dipolar field remains.

The magnetic field generated by electron 1 is

$
arrow(B)_1(arrow(r))
= mu_0 / (4 pi r^3)
  [3 (arrow(mu)_1 dot hat(r)) hat(r) - arrow(mu)_1],
quad hat(r) = arrow(r) / r.
$

A second electron at $arrow(r)$ has magnetic moment $arrow(mu)_2$. Its energy in
this field is

$
U
= -arrow(mu)_2 dot arrow(B)_1(arrow(r))
= mu_0 / (4 pi r^3)
  [-arrow(mu)_1 dot arrow(mu)_2 + 3 (arrow(mu)_1 dot hat(r))(arrow(mu)_2 dot hat(r))].
$

Now promote $U -> hat(H)_("ZFS")$. Use

$
hat(arrow(mu))_i = -g_e mu_B hat(arrow(S))_i / planck,
quad mu_B = (e planck) / (2 m_e).
$

Replacing $arrow(mu)_(1,2)$ with $hat(arrow(mu))_(1,2)$ gives

$
hat(H)_("ZFS")
= -mu_0 / (4 pi) (g_e mu_B)^2 / planck^2 1 / r^3
  [-hat(arrow(S))_1 dot hat(arrow(S))_2
   + 3 (hat(arrow(S))_1 dot hat(r))(hat(arrow(S))_2 dot hat(r))].
$

Equivalently,

$
hat(H)_("ZFS")
= mu_0 / (4 pi) (g_e mu_B)^2 / planck^2 1 / r^3
  [hat(arrow(S))_1 dot hat(arrow(S))_2
   - 3 (hat(arrow(S))_1 dot hat(r))(hat(arrow(S))_2 dot hat(r))].
$

To put this into a tensor form, expand the dot products. For $i, j in (x, y, z)$,

$
arrow(S)_1 dot arrow(S)_2 = sum_(i in (x, y, z)) S_(1 i) S_(2 i),
$

$
(arrow(S)_1 dot hat(r))(arrow(S)_2 dot hat(r))
= (sum_i S_(1 i) hat(r)_i)(sum_j S_(2 j) hat(r)_j)
= sum_(i, j) S_(1 i) (hat(r)_i hat(r)_j) S_(2 j)
= sum_(i, j) S_(1 i) ((r_i r_j) / r^2) S_(2 j).
$

Substitute into the Hamiltonian:

$
hat(H)_("ZFS")
= mu_0 / (4 pi) (g_e mu_B)^2 / planck^2 1 / r^3
  ( sum_i S_(1 i) S_(2 i) - 3 sum_(i, j) S_(1 i) ((r_i r_j) / r^2) S_(2 j) ).
$

Rewrite the first sum using $delta_(i j)$:

$
hat(H)_("ZFS")
= mu_0 / (4 pi) (g_e mu_B)^2 / planck^2
  ( sum_(i, j) (delta_(i j) / r^3) S_(1 i) S_(2 j)
    - 3 sum_(i, j) ((r_i r_j )/ r^5) S_(1 i) S_(2 j) ).
$

So

$
hat(H)_("ZFS")
= sum_(i, j) S_(1 i)
  [ mu_0 / (4 pi) (g_e mu_B)^2 / planck^2 (delta_(i j) / r^3 - (3 r_i r_j) / r^5) ]
  S_(2 j).
$

Define the tensor $D_(i j)$:

#box(
  fill: luma(250),
  inset: 10pt,
  width: 100%,
  [
$
D_(i j)(arrow(r))
= (mu_0 / (4 pi)) ((g_e mu_B)^2 / planck^2)
  (delta_(i j) / r^3 - (3 r_i r_j) / r^5).
$
  ],
)

Then the ZFS Hamiltonian is

$
hat(H)_("ZFS")
= sum_(i, j in (x, y, z)) S_(1 i) \, D_(i j)(arrow(r)) \, S_(2 j)
= hat(arrow(S))_1 dot D dot hat(arrow(S))_2.
$

== D and E

The tensor in parentheses is traceless. Taking the trace,

$
sum_i (delta_(i i) / r^3 -( 3 r_i r_i) / r^5)
= sum_i 1 / r^3 - 3 sum_i r_i^2 / r^5
= 3 / r^3 - 3 / r^5(r_x^2 + r_y^2 + r_z^2)
= 0.
$

So if we diagonalize $D$ in the defect’s principal axes, we can write

$
D_(i j) = mat(
  D_x, 0, 0;
  0, D_y, 0;
  0, 0, D_z;
),
quad D_x + D_y + D_z = 0.
$

For the silicon vacancy $V_(upright("Si"))^- in C_(3 V)$, symmetry gives $D_x = D_y$.
Together with tracelessness, $2 D_x + D_z = 0$, so

$
D_x = D_y = -1/2 D_z.
$

Define scalars $D, E$ by

$
D = 3/2 D_z,
quad
E = 1/2(D_x - D_y).
$

$D$ measures axial splitting. $E$ measures deviation from perfect axial symmetry.
In practice, $E approx 0$.

Then

$
D_("diag")
= mat(
  D_x, 0, 0;
  0, D_y, 0;
  0, 0, D_z;
)
= mat(
  -D/3 + E, 0, 0;
  0, -D/3 - E, 0;
  0, 0, 2/3 D;
).
$

== Raising and Lowering

From $hat(H)_("ZFS") = hat(arrow(S)) dot D dot hat(arrow(S))$, expanding in the
principal axes gives

$
hat(H)_("ZFS")
= (-D/3 + E) hat(S)_x^2
+ (-D/3 - E) hat(S)_y^2
+ 2/3 D hat(S)_z^2
$

$
= D (hat(S)_z^2 - 1/3(hat(S)_x^2 + hat(S)_y^2 + hat(S)_z^2))
+ E (hat(S)_x^2 - hat(S)_y^2).
$

The Cartesian operators relate to raising and lowering via

$
hat(S)_+ |s, m⟩
= (hat(S)_x + i hat(S)_y) |s, m⟩
= sqrt(s(s+1) - m(m+1)) |s, m+1⟩,
$

$
hat(S)_- |s, m⟩
= (hat(S)_x - i hat(S)_y) |s, m⟩
= sqrt(s(s+1) - m(m-1)) |s, m-1⟩.
$

Putting this together yields a compact action of $hat(H)_("ZFS")$ on $|s, m⟩$:

#box(
  fill: luma(250),
  inset: 10pt,
  width: 100%,
  [
$
hat(H)_("ZFS") |s, m⟩
&= D m^2 |s, m⟩ - D/3s(s+1) |s, m⟩ \ 
&+ E/2(s(s+1) - m(m+1)) |s, m+2⟩ \
&+ E/2(s(s+1) - m(m-1)) |s, m-2⟩.
$
  ],
)

ZFS splits levels even when no external $B$ field is applied. It also introduces
$m -> m ± 2$ mixing, which leads to weak “forbidden” transitions and a faint
half-field response in EDMR spectra. A simulation that resolves half-field
features needs to include ZFS accurately.

